### ISSUE TITLE
Does it support templates from Car App Library?

### ISSUE THREAD

**Issue by maxrimmer** [snappautomotive/device_snappautomotive_vim3#2]
Hi,
Great to finally see the developer kit come out!

Quick questions:
* Does it support templates from the Car App Library (e.g: NavigationTemplate, MessageTemplate etc.
* Does the board have native GPS support? If not, do you have a recommended GPS module?

**Comment by alsutton** [comment]
Thanks for the kidn words.

* Does it support templates from the Car App Library (e.g: NavigationTemplate, MessageTemplate etc.

It currently doesn't support all the templates because some of them require integration with components which can not be sourced at the current time. 

One example of this is the `NavigationTemplate`; The AOSP reference build does not have a map implementation, and we've put our lightweight wrapper around OpenStreetMap in so that folk don't just see a green box where the map is supposed to be. 

If you're working with a mapping provider, they should be able to provide you with an apk you can install to replace SnappMaps with a more fully featured map system that integrates with the templates. If that's not the case then please feel free to submit PRs to https://github.com/snappautomotive/SnappMaps to create that functionality.

* Does the board have native GPS support? If not, do you have a recommended GPS module?

The board does not have native GPS onboard. We're looking at a few USB options to see which ones we'd recommend, and would be happy to hear about any experience you have with them
